name: Push to nuget feed on release

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [regress_update]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        #src: https://github.com/marketplace/actions/download-workflow-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.dll_pat }}
          workflow: build.yml
          branch: master
          path: .
          repo: TaleSpire-Modding/AutomationDlls
      - run: |
          cd dlls
          dir
          cd ..

      - name: build
        run: |
          dir
          cd AssetToolTipPlugin
          dir
          dotnet restore AssetToolTipPluginPipeline.csproj
          dotnet build AssetToolTipPluginPipeline.csproj

      - uses: actions/upload-artifact@master
        with:
          name: AssetToolTip
          path: AssetToolTipPlugin\bin\Debug\AssetToolTip.dll
      
      - uses: actions/upload-artifact@master
        with:
          name: dlls
          path: AssetToolTipPlugin\bin\Debug\AssetToolTip.dll

      # Now need to write a deploy procedure after the Build
